import '@/styles/globals.css'

import Header from '@/components/Header'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-light">
        <Header />
        {children}
        <footer className="r-grid bg-black h-[106px] z-20">Hola</footer>
      </body>
    </html>
  )
}
