import '@/styles/globals.css'
import 'react-toastify/dist/ReactToastify.css'

import Header from '@/components/Header'
import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-light relative">
        <Header />
        {children}
        <ToastContainer />

        <div className="blur-right-mobile"></div>
      </body>
    </html>
  )
}
